name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
